"""files table

Revision ID: 1788569368d2
Revises: de2d9f31df83
Create Date: 2025-08-16 22:10:17.893869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1788569368d2'
down_revision: Union[str, Sequence[str], None] = 'de2d9f31df83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create the files table since other tables already exist
    op.create_table('files',
    sa.Column('storage', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('scan_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index('ix_files_org_created', 'files', ['org_id', 'created_at'], unique=False)
    
    # Enable RLS and create tenant isolation policy
    op.execute("ALTER TABLE files ENABLE ROW LEVEL SECURITY;")
    op.execute("""
    CREATE POLICY tenant_isolation ON files
    USING (org_id::text = current_setting('app.current_org_id', true));
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RLS policy and disable RLS
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON files;")
    op.execute("ALTER TABLE files DISABLE ROW LEVEL SECURITY;")
    
    op.drop_index('ix_files_org_created', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
