"""init core tables + RLS

Revision ID: 237de525dbea
Revises: 0ccb6821a00d
Create Date: 2025-08-14 19:30:19.650278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237de525dbea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ... (autogenerated tables)
    # Add Postgres helper GUC setter
    op.execute("""
    CREATE OR REPLACE FUNCTION set_org_id(org uuid) RETURNS void
    LANGUAGE sql AS $$
      SELECT set_config('app.current_org_id', org::text, true);
    $$;
    """)

    # Enable RLS on org-scoped tables
    for table in ('memberships',):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"""
        CREATE POLICY tenant_isolation ON {table}
        USING (org_id::text = current_setting('app.current_org_id', true));
        """)

def downgrade():
    for table in ('memberships',):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP FUNCTION IF EXISTS set_org_id(uuid);")
