"""init core tables + RLS

Revision ID: 53979fc6e0af
Revises: 062b4e59520a
Create Date: 2025-08-14 23:43:56.546019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53979fc6e0af'
down_revision: Union[str, Sequence[str], None] = '062b4e59520a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'ord_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('ord_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
